### ISSUE TITLE
First Issue - Running the Script

### ISSUE THREAD

**Issue by IsaacCoulter** [aurasphere/ffx-thunder-dodger#1]
Hi, 

Not sure if this is the right forum for this, but was hoping someone could help. I am hoping you run the script in CMD, I have installed GIT desktop and JDK, however when I run the script I am getting 2 errors, 

![image](https://user-images.githubusercontent.com/73482423/97184373-bd190980-1796-11eb-9593-05cc80774ba3.png)

Have I done something wrong? The user instructions, make is seems so simple. Am I over complicating things?

Apologies in advance for being such a massive nooooob!

**Comment by aurasphere** [comment]
Hey @IsaacCoulter ! Actually the error you found is because you need to compile the code before you can run it. I honestly didn't think that anybody would use this program, so I didn't bother, but I'll add a binary version with more detailed instructions for you as soon as possible.

**Comment by aurasphere** [comment]
Actually I've already updated it, so you should now be able to run it! Let me know if you find any more troubles and have a nice day!
