### ISSUE TITLE
Chiaki

### ISSUE THREAD

**Issue by whitezombie2000** [aurasphere/ffx-thunder-dodger#2]
Will it work with Chiaki? I run 5.05 so I was just curious if you know?

**Comment by aurasphere** [comment]
Hey @whitezombie2000 unfortunately I don't know what Chiaki is so I can't tell

**Comment by whitezombie2000** [comment]
Chiaki is an opensource version of PS Remote Play.

**Comment by whitezombie2000** [comment]
Got around to testing this on a play through. The script is very buggy when using Chiaki. It randomly seems to work but you get hit by lighting a lot. It also seem to press random buttons if you go into battle or the menu. Tested the script with PS4 Remote Play, the script worked flawlessly on a wired connection, and even over wireless connection.
![lightning_dancer](https://user-images.githubusercontent.com/23583562/147860261-b976b7d7-8e36-4053-bb06-dddc38d81a5e.JPG)
